### ISSUE TITLE
NPM install fails in node v0.10.22

### ISSUE THREAD

**Issue by jascination** [trevnorris/node-ofe#3] opened 2013-11-13 11:19 UTC
Getting his error when trying to load with the newest version of Node (0.10.22):

```
    npm http GET https://registry.npmjs.org/ofe
    npm http 200 https://registry.npmjs.org/ofe
    npm http GET https://registry.npmjs.org/ofe/-/ofe-0.1.2.tgz
    npm http 200 https://registry.npmjs.org/ofe/-/ofe-0.1.2.tgz

    > ofe@0.1.2 install /node_modules/ofe
    > node-gyp rebuild

    gyp http GET http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
    gyp http 200 http://nodejs.org/dist/v0.10.22/node-v0.10.22.tar.gz
    xcrun: error: active developer path ("/Library/Developer") does not exist, use xcode-select to change

    gyp: Error 1 running xcodebuild
    gyp ERR! configure error 
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/.nvm/v0.10.22/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:467:16)
    gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
    gyp ERR! System Darwin 13.0.0
    gyp ERR! command "node" "/.nvm/v0.10.22/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /node_modules/ofe
    gyp ERR! node -v v0.10.22
    gyp ERR! node-gyp -v v0.11.0
    gyp ERR! not ok 
    npm ERR! ofe@0.1.2 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ofe@0.1.2 install script.
    npm ERR! This is most likely a problem with the ofe package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     node-gyp rebuild
    npm ERR! You can get their info via:
    npm ERR!     npm owner ls ofe
    npm ERR! There is likely additional logging output above.

    npm ERR! System Darwin 13.0.0
    npm ERR! command "/.nvm/v0.10.22/bin/node" "/.nvm/v0.10.22/bin/npm" "install" "ofe"
    npm ERR! cwd /
    npm ERR! node -v v0.10.22
    npm ERR! npm -v 1.3.14
    npm ERR! code ELIFECYCLE
    npm ERR! 
    npm ERR! Additional logging details can be found in:
    npm ERR!     /npm-debug.log
    npm ERR! not ok code 0        
```

**Comment by jpepper07** [comment] 2016-03-09 06:47
Still no fix?

**Comment by trevnorris** [comment] 2016-03-09 23:45
@jpepper07 I'm not sure there is a code fix. At least, it's not an issue I've been able to reproduce. Seems to involve the build environment.

**Comment by aiboy** [comment] 2017-01-09 19:15
It's x-code issue (people simply have not valid or correctly configured xcode developer tools - without them native dependencies could not compile)

StackTrace have clear indication on what is wrong
> xcrun: error: active developer path ("/Library/Developer") does not exist, use xcode-select to change

And Google have plenty of information about this issue
http://stackoverflow.com/questions/11456918/change-xcrun-developer-path

I suggest to close this issue since it's dons't look like a library problem.

**Comment by trevnorris** [comment] 2017-01-11 17:15
@aiboy thanks. for the info. will do.

**Closed by trevnorris** 2017-01-11 17:15 UTC
